version: "3"

networks:
  gd-network:
    driver: bridge

services:
  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile.dev
    depends_on:
      - db
    networks:
      - gd-network
    expose:
      - "${GD_API_SERVER_PORT}"
    ports:
      - "${GD_API_SERVER_PORT}:${GD_API_SERVER_PORT}"
    restart: on-failure
    container_name: server
    volumes:
      - .:/home/app/generatedata
      - /home/app/generatedata/node_modules

  db:
    image: mariadb:10.5.8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "${GD_DB_PORT}"
    ports:
      - "${GD_DB_PORT}:${GD_DB_PORT}"
    networks:
      - gd-network
    environment:
      MYSQL_ROOT_PASSWORD: ${GD_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${GD_DB_NAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
    volumes:
      - ./server/database/dbStructure.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./data/db:/var/lib/mysql


# --------------------------------------------------

#  webapp:
#    build:
#      context: ./client
#      dockerfile: Dockerfile.dev
#    expose:
#      - 9000
#    ports:
#      - 9000:9000
#    container_name: webapp
#    volumes:
#      - ./client:/home/app/generatedata/client
#      - /home/app/generatedata/client/node_modules
#    links:
#      - server
#    command: yarn webpackDev
    # *** For prod only.
#    nginx:
#      image: nginx:latest
#      container_name: prod_nginx
#      depends_on:
#        - web
#      volumes:
#        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
#      ports:
#        - 80:80
#        - 443:443

    ## this may be useful
#    environment:
#      - PGUSER=postgres
#      - PGHOST=postgres
#      - PGDATABASE=postgres
#      - PGPASSWORD=
#      - PGPORT=5432
